app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User, Projet, Taches, Equipes, Employes, Rapports
from . import db

bp = Blueprint('main', __name__)


@bp.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        # Vérification des informations d'identification
        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            session['username'] = user.nom  # Stocker le nom d'utilisateur dans la session
            return redirect(url_for('main.dashboard', username=user.nom))
        else:
            flash("Identifiants invalides.")  # Message d'erreur si les identifiants sont incorrects

    return render_template('index.html')


@bp.route('/inscrire', methods=['GET', 'POST'])
def inscription():
    if request.method == 'POST':
        nom = request.form['nom']
        email = request.form['email']
        password = request.form['password']
        confirmpassword = request.form['confirmer']

        # Vérification des mots de passe
        if password != confirmpassword:
            return render_template('inscription.html', error="Les mots de passe ne correspondent pas.")

        # Vérification de l'email existant
        if User.query.filter_by(email=email).first():
            return render_template('inscription.html', error="Cet email est déjà utilisé.")

        # Création d'un nouvel utilisateur
        new_user = User(nom=nom, email=email, password=generate_password_hash(password))
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('inscription.html')


"""@bp.route('/bienvenue/<username>')
def bienvenue(username):
    return render_template('bienvenue.html', username=username)"""


@bp.route('/dashboard')
def dashboard():
    if 'username' not in session:
        return redirect(url_for('main.index'))  # Rediriger vers la page d'accueil si non connecté
    return render_template('dashboard.html', username=session['username'])


@bp.route('/logout')
def logout():
    session.pop('username', None)
    flash("Vous êtes déconnecté.")  # Message de déconnexion
    return redirect(url_for('main.index'))  # Rediriger vers la page d'accueil après déconnexion


@bp.route('/projet')
def projet():
    # Récupérer tous les projets
    projet = Projet.query.all()
    # Récupérer tous les taches
    tache = Taches.query.all()  # Remplace 'Projet' par le nom de ton modèle
    return render_template('projet.html', projets=projet, taches=tache)


@bp.route('/taches')
def taches():
    # Récupérer tous les taches
    tache_list = Taches.query.all()  # Remplace 'Taches' par le nom de ton modèle
    # Récupérer tous les projets
    projet = Projet.query.all()  # Remplace 'Projet' par le nom de ton modèle
    # Récupérer tous les employes
    employe = Employes.query.all()  # Remplace 'Projet' par le nom de ton modèle
    return render_template('taches.html', taches=tache_list, projets=projet, employes=employe)


@bp.route('/equipes')
def equipes():
    # Récupérer toutes les équipes
    equipes_list = Equipes.query.all()  # Remplace 'Equipes' par le nom de ton modèle

    # Récupérer tous les employés
    #employe_list = Employes.query.all()  # Remplace 'Employes' par le nom de ton modèle

    # Récupérer tous les projets
    projet = Projet.query.all()  # Remplace 'Projet' par le nom de ton modèle

    return render_template('equipes.html', equipes=equipes_list, projets=projet)


@bp.route('/employes')
def employes():
    # Récupérer toutes les equipes
    equipes_list = Equipes.query.all()  # Remplace 'Equipes' par le nom de ton modèle

    # Récupérer tous les employés
    employe_list = Employes.query.all()  # Remplace 'Employe' par le nom de ton modèle
    return render_template('employes.html', equipes=equipes_list, employes=employe_list)


@bp.route('/rapports')
def rapports():
    # Récupérer tous les projets
    rapport = Rapports.query.all()
    return render_template('rapports.html', rapports=rapport)


@bp.route('/modalprojet', methods=['POST', 'GET'])
def modalprojet():
    if request.method == 'POST':
        nom = request.form['nom']
        description = request.form['description']
        date_debut = request.form['date_debut']
        date_fin = request.form['date_fin']
        client = request.form['client']

        # verification du projet existant
        if Projet.query.filter_by(nom=nom).first():
            return render_template('projet.html', error="ce pojet existe deja")

        # creation d un nouveau projet
        new_projet = Projet(nom=nom, description=description, date_debut=date_debut, date_fin=date_fin, client=client)
        db.session.add(new_projet)
        db.session.commit()

        return redirect(url_for('main.projet'))
    return render_template('projet.html')


@bp.route('/modaltaches', methods=['POST', 'GET'])
def modaltaches():
    if request.method == 'POST':
        nom = request.form['nom']
        description = request.form['description']
        date_debut = request.form['date_debut']
        date_fin = request.form['date_fin']
        projet = request.form['projet']
        employes = request.form['employes']

        # Vérification du projet existant
        if Taches.query.filter_by(nom=nom).first():  # Utilisation correcte du modèle
            return render_template('taches.html', error="cette tache existe déjà")

        # Création d'une nouvelle tâche
        new_taches = Taches(nom=nom, description=description, date_debut=date_debut, date_fin=date_fin, projet_id=projet,
                            employe_id=employes)
        db.session.add(new_taches)
        db.session.commit()

        return redirect(url_for('main.taches'))
    employes = Taches.query.all()
    projet = Taches.query.all()
    return render_template('taches.html', employes=employes, projet=projet)




@bp.route('/modalequipes', methods=['POST', 'GET'])
def modalequipes():
    if request.method == 'POST':
        nom = request.form['nom']
        projet_id = request.form['projet']

        # Vérification d'une équipe existante
        if Equipes.query.filter_by(nom=nom).first():  # Utilisation correcte du modèle
            return render_template('equipes.html', error="cette équipe existe déjà")

        # Création d'une nouvelle équipe
        new_equipes = Equipes(nom=nom, projet_id=projet_id)
        db.session.add(new_equipes)
        db.session.commit()



        return redirect(url_for('main.equipes'))
    projet=Projet.query.all()
    return render_template('equipes.html', projet=projet)


@bp.route('/modalemployes', methods=['POST', 'GET'])
def modalemployes():
    if request.method == 'POST':
        nom = request.form['nom']
        email = request.form['email']
        poste = request.form['poste']
        equipes_id = request.form['equipes']


        # Vérification d'un employé existant
        if Employes.query.filter_by(nom=nom).first():  # Utilisation correcte du modèle
            return render_template('employes.html', error="cet employé existe déjà")

        # Création d'un nouvel employé
        new_employes = Employes(nom=nom, email=email, poste=poste, equipe_id=equipes_id,)
        db.session.add(new_employes)
        db.session.commit()

        return redirect(url_for('main.employes'))
    equipes=Equipes.query.all()
    return render_template('employes.html', equipes=equipes,)


@bp.route('/parametre')
def parametre():
    return render_template('parametre.html')

app/templates/includes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://unicons.iconscout.com/release/v4.0.8/css/line.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/2.1.4/css/dataTables.bootstrap5.css" rel="stylesheet">
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" rel="stylesheet">

    <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/modal.css') }}" rel="stylesheet">

    <title>ProjetTracking - {% block title %}{% endblock %}</title>
</head>
<body class="_dark">
{% block content %}{% endblock content %}

<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.1.4/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.1.4/js/dataTables.bootstrap5.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

<script src="{{ url_for('static', filename='js/javascript.js') }}"></script>

<!--
espace pour ajouter le code javascript
-->
{% block javascripts %}{% endblock javascripts %}
<script>
    document.addEventListener("DOMContentLoaded", () => {
        const body = document.querySelector("body"),
              modeToggle = document.getElementById("mode-toggle");

        modeToggle.addEventListener("change", () => {
            body.classList.toggle("dark", modeToggle.checked);
        });
    });

    //data table
    new DataTable('#example');

</script>
</body>
</html>

app/templates/includes/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://unicons.iconscout.com/release/v4.0.8/css/line.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/2.1.4/css/dataTables.bootstrap5.css" rel="stylesheet">
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" rel="stylesheet">

    <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/modal.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/card_d.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/parametre.css') }}" rel="stylesheet">

    <title>ProjetTracking - {% block title %}{% endblock %}</title>
</head>
<body class="_dark">
{% block content %}{% endblock content %}

<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.1.4/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.1.4/js/dataTables.bootstrap5.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

<script src="{{ url_for('static', filename='js/javascript.js') }}"></script>

<!--
espace pour ajouter le code javascript
-->
{% block javascripts %}{% endblock javascripts %}
<script>
    document.addEventListener("DOMContentLoaded", () => {
        const body = document.querySelector("body"),
              modeToggle = document.getElementById("mode-toggle");

        modeToggle.addEventListener("change", () => {
            body.classList.toggle("dark", modeToggle.checked);
        });
    });

    //data table
    new DataTable('#example');

</script>
</body>
</html>

app/templates/includes/navbar.html
<!-- NAVBAR -->
<nav>
    <form action="#">
        <div class="form-group">
            <input placeholder="search..." type="text">
            <i class='bx bx-search icon'></i>
        </div>
    </form>
    <a class="nav-link" href="#">
        <i class='bx bxs-bell'></i>
        <span class="badge">5</span>
    </a>
    <a class="nav-link" href="#">
        <i class='bx bxs-message-square-dots'></i>
        <span class="badge">8</span>
    </a>
    <span class="divider"></span>
    <div class="profile">
        <img alt=""
             src="{{ url_for('static', filename='image/p1.jpg') }}">
        <ul class="profile-link">
            <li><a href="#"><i class='bx bx-user-circle icon'></i> Profil</a></li>
            <li><a href="#"><i class='bx bxs-cog'></i> Paramètre</a></li>
            <li><a class="active" href="{{ url_for('main.logout') }}">
                <i class='bx bx-log-in'></i>
                <span class="link-name">Deconnexion</span>
            </a></li>

        </ul>
        <span style="color:black; align-item:center; justufy-content:center">{{ session['username'] }}</span>
    </div>
</nav>
<!-- NAVBAR -->

app/templates/includes/sidebar.html
<!--SIDEBAR-->
<section id="sidebar">
    <a class="brand" href="#"><i class='bx bx-exit-fullscreen'></i>CodingLab</a>
    <ul class="side-menu">
        <li><a class="active"  href="{{ url_for('main.dashboard') }}"><i class='bx bxs-dashboard icon'></i> Dashboard</a></li>
        <li class="divider">Main</li>
        <li>
            <a href="{{ url_for('main.projet') }}"><i class='bx bxs-package icon'></i> Projets </a>
        </li>
        <li><a href="{{ url_for('main.taches') }}"><i class='bx bx-task icon'></i> Taches</a></li>
        <li><a href="{{ url_for('main.equipes') }}"><i class='bx bxs-user-account icon'></i> Equipes</a>
        <li><a href="{{ url_for('main.employes') }}"><i class='bx bxs-user icon'></i> Employés</a></li>
        <li><a href="{{ url_for('main.rapports') }}"><i class='bx bxs-report icon'></i> Rapports</a></li>
        <li class="divider">Administrateur</li>
        <li><a href="{{ url_for('main.parametre') }}"><i class='bx bx-cog icon'></i> Parametre </a></li>
        <!--<li>
            <a href="#"><i class='bx bxs-notepad icon'></i> Forms <i class='bx bx-chevron-right icon-right'></i></a>
            <ul class="side-dropdown">
                <li><a href="#">Basic</a></li>
                <li><a href="#">Select</a></li>
                <li><a href="#">Checkbox</a></li>
                <li><a href="#">Radio</a></li>
            </ul>
        </li> -->
    </ul>
    <ul class="logout-mode">
        <li><a class="active"  href="{{ url_for('main.logout') }}">
            <i class='bx bx-log-in'></i>
            <span class="link-name">Deconnexion</span>
        </a></li>

        <li class="mode">
            <label class="switch">
                <input checked id="mode-toggle" type="checkbox">
                <span class="slider round"></span>
            </label>
            <span class="link-name">Dark Mode</span>
        </li>
        </div>
    </ul>
</section>
<!-- SIDEBAR -->