app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User, Projet, Taches, Equipes, Employes, Rapports
from . import db

bp = Blueprint('main', __name__)


@bp.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        # Vérification des informations d'identification
        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            session['username'] = user.nom  # Stocker le nom d'utilisateur dans la session
            return redirect(url_for('main.dashboard', username=user.nom))
        else:
            flash("Identifiants invalides.")  # Message d'erreur si les identifiants sont incorrects

    return render_template('index.html')


@bp.route('/inscrire', methods=['GET', 'POST'])
def inscription():
    if request.method == 'POST':
        nom = request.form['nom']
        email = request.form['email']
        password = request.form['password']
        confirmpassword = request.form['confirmer']

        # Vérification des mots de passe
        if password != confirmpassword:
            return render_template('inscription.html', error="Les mots de passe ne correspondent pas.")

        # Vérification de l'email existant
        if User.query.filter_by(email=email).first():
            return render_template('inscription.html', error="Cet email est déjà utilisé.")

        # Création d'un nouvel utilisateur
        new_user = User(nom=nom, email=email, password=generate_password_hash(password))
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('inscription.html')


"""@bp.route('/bienvenue/<username>')
def bienvenue(username):
    return render_template('bienvenue.html', username=username)"""


@bp.route('/dashboard')
def dashboard():
    if 'username' not in session:
        return redirect(url_for('main.index'))  # Rediriger vers la page d'accueil si non connecté
    return render_template('dashboard.html', username=session['username'])


@bp.route('/logout')
def logout():
    session.pop('username', None)
    flash("Vous êtes déconnecté.")  # Message de déconnexion
    return redirect(url_for('main.index'))  # Rediriger vers la page d'accueil après déconnexion


@bp.route('/projet')
def projet():
    # Récupérer tous les projets
    projet = Projet.query.all()
    # Récupérer tous les taches
    tache = Taches.query.all()  # Remplace 'Projet' par le nom de ton modèle
    return render_template('projet.html', projets=projet, taches=tache)


@bp.route('/taches')
def taches():
    # Récupérer tous les taches
    tache_list = Taches.query.all()  # Remplace 'Taches' par le nom de ton modèle
    # Récupérer tous les projets
    projet = Projet.query.all()  # Remplace 'Projet' par le nom de ton modèle
    # Récupérer tous les employes
    employe = Employes.query.all()  # Remplace 'Projet' par le nom de ton modèle
    return render_template('taches.html', taches=tache_list, projets=projet, employes=employe)


@bp.route('/equipes')
def equipes():
    # Récupérer toutes les équipes
    equipes_list = Equipes.query.all()  # Remplace 'Equipes' par le nom de ton modèle

    # Récupérer tous les employés
    #employe_list = Employes.query.all()  # Remplace 'Employes' par le nom de ton modèle

    # Récupérer tous les projets
    projet = Projet.query.all()  # Remplace 'Projet' par le nom de ton modèle

    return render_template('equipes.html', equipes=equipes_list, projets=projet)


@bp.route('/employes')
def employes():
    # Récupérer toutes les equipes
    equipes_list = Equipes.query.all()  # Remplace 'Equipes' par le nom de ton modèle

    # Récupérer tous les employés
    employe_list = Employes.query.all()  # Remplace 'Employe' par le nom de ton modèle
    return render_template('employes.html', equipes=equipes_list, employes=employe_list)


@bp.route('/rapports')
def rapports():
    # Récupérer tous les projets
    rapport = Rapports.query.all()
    return render_template('rapports.html', rapports=rapport)


@bp.route('/modalprojet', methods=['POST', 'GET'])
def modalprojet():
    if request.method == 'POST':
        nom = request.form['nom']
        description = request.form['description']
        date_debut = request.form['date_debut']
        date_fin = request.form['date_fin']
        client = request.form['client']

        # verification du projet existant
        if Projet.query.filter_by(nom=nom).first():
            return render_template('projet.html', error="ce pojet existe deja")

        # creation d un nouveau projet
        new_projet = Projet(nom=nom, description=description, date_debut=date_debut, date_fin=date_fin, client=client)
        db.session.add(new_projet)
        db.session.commit()

        return redirect(url_for('main.projet'))
    return render_template('projet.html')


@bp.route('/modaltaches', methods=['POST', 'GET'])
def modaltaches():
    if request.method == 'POST':
        nom = request.form['nom']
        description = request.form['description']
        date_debut = request.form['date_debut']
        date_fin = request.form['date_fin']
        projet = request.form['projet']
        employes = request.form['employes']

        # Vérification du projet existant
        if Taches.query.filter_by(nom=nom).first():  # Utilisation correcte du modèle
            return render_template('taches.html', error="cette tache existe déjà")

        # Création d'une nouvelle tâche
        new_taches = Taches(nom=nom, description=description, date_debut=date_debut, date_fin=date_fin, projet_id=projet,
                            employe_id=employes)
        db.session.add(new_taches)
        db.session.commit()

        return redirect(url_for('main.taches'))
    employes = Taches.query.all()
    projet = Taches.query.all()
    return render_template('taches.html', employes=employes, projet=projet)




@bp.route('/modalequipes', methods=['POST', 'GET'])
def modalequipes():
    if request.method == 'POST':
        nom = request.form['nom']
        projet_id = request.form['projet']

        # Vérification d'une équipe existante
        if Equipes.query.filter_by(nom=nom).first():  # Utilisation correcte du modèle
            return render_template('equipes.html', error="cette équipe existe déjà")

        # Création d'une nouvelle équipe
        new_equipes = Equipes(nom=nom, projet_id=projet_id)
        db.session.add(new_equipes)
        db.session.commit()



        return redirect(url_for('main.equipes'))
    projet=Projet.query.all()
    return render_template('equipes.html', projet=projet)


@bp.route('/modalemployes', methods=['POST', 'GET'])
def modalemployes():
    if request.method == 'POST':
        nom = request.form['nom']
        email = request.form['email']
        poste = request.form['poste']
        equipes_id = request.form['equipes']


        # Vérification d'un employé existant
        if Employes.query.filter_by(nom=nom).first():  # Utilisation correcte du modèle
            return render_template('employes.html', error="cet employé existe déjà")

        # Création d'un nouvel employé
        new_employes = Employes(nom=nom, email=email, poste=poste, equipe_id=equipes_id,)
        db.session.add(new_employes)
        db.session.commit()

        return redirect(url_for('main.employes'))
    equipes=Equipes.query.all()
    return render_template('employes.html', equipes=equipes,)


@bp.route('/parametre')
def parametre():
    return render_template('parametre.html')

app/templates/bienvenue.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenue</title>
</head>
<body>
    <h1>Bienvenue, {{ username }}!</h1>
    <p>Vous êtes maintenant connecté.</p>
    <a href="{{ url_for('main.index') }}">Retour à l'accueil</a>
</body>
</html>

app/templates/employes.html
{% extends 'includes/base.html' %}


{% block title %}Employes{% endblock title %}

{% block content %}
<!--SIDEBAR-->
{% include 'includes/sidebar.html' %}
<!-- SIDEBAR -->

<section id="content">
    <!-- NAVBAR -->
    {% include 'includes/navbar.html' %}
    <!-- NAVBAR -->


    <!-- MAIN -->
    <main>
        <!-- <h1 class="title">Employes</h1>
         <ul class="breadcrumbs">
            <li><a href="#">Accueil</a></li>
            <li class="divider">/</li>
            <li><a class="active" href="#">Dashboard</a></li>
        </ul> -->
        <div class="div-bouton">
            <button data-bs-target="#exampleModal" data-bs-toggle="modal"><i class='bx bxs-plus-circle icon'></i>Créer
                un employe
            </button>
        </div>
        <!-- data Table -->
        <div class="title">
            <i class="uil uil-clock-three"></i>
            <span class="text">Listes des Employes</span>
        </div>

        <table class="table table-striped" id="example" style="width:100%">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Email</th>
                <th>poste</th>
                <th>equipes</th>
            </tr>
            </thead>
            <tbody>
            {% for employe in employes %}
            <tr>
                <td>{{ employe.nom }}</td>
                <td>{{ employe.email }}</td>
                <td>{{ employe.poste }}</td>
                <td>{{ employe.equipe.nom}}</td>

            </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th>Nom</th>
                <th>Email</th>
                <th>Poste</th>
                <th>Equipes</th>

            </tr>
            </tfoot>
        </table>
        <!-- data Table -->

        <!-- formulaire modal -->

        <form action="{{ url_for('main.modalemployes') }}" method="post">
            <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="exampleModal"
                 tabindex="-1">
                <div class="modal-dialog modal-dialog-scrollable">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">employes</h5>
                            <button aria-label="Close" class="btn-close" data-bs-dismiss="modal" type="button"></button>
                        </div>
                        <div class="modal-body">

                            <div class="mb-3">
                                <label class="form-label" for="exampleInputEmail1"> employe </label>
                                <input aria-describedby="emailHelp" class="form-control" id="exampleInputEmail1"
                                       name="nom"
                                       type="text">
                            </div>

                            <div class="mb-3">
                                <label class="form-label" for="exampleInputEmail1"> email </label>
                                <input aria-describedby="emailHelp" class="form-control" id="examplInputEmail1"
                                       name="email"
                                       type="email">
                            </div>

                            <div class="mb-3">
                                <label class="form-label" for="exampleInputEmail1"> poste </label>
                                <input aria-describedby="emailHelp" class="form-control" id="exampInputEmail1"
                                       name="poste"
                                       type="text">

                                <div class="mb-3">
                            <label class="form-label" for="teamSelect"> equipes :</label>
                            <select class="form-select" id="teamSelect" name="equipes" required>

                                <option value="">Sélectionnez une equipe</option>
                                {% for equipe in equipes %}
                                <option value="{{ equipe.id }}">{{ equipe.nom }}</option>
                                {% endfor %}
                            </select>
                                </div>
                            </div>
                        </div>



                        <div class="modal-footer">
                            <button button class="btn btn-secondary" data-bs-dismiss="modal"
                                    style="background-color: #D3D3D3;"
                                    type="button">Close
                            </button>
                            <button class="btn btn-primary" style="background-color: #eb7371; "
                                    type="submit">Save
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!-- formulaire modal -->
    </main>
    <!-- MAIN -->
</section>
{% endblock content %}

{% block javascripts %}
<script>
    var modal = document.getElementById("myModal");
    var btn = document.getElementById("openModal");
    var span = document.getElementsByClassName("close")[0];

    btn.onclick = function() {
        modal.style.display = "block";
    }

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
{% endblock javascripts %}

app/templates/equipes.html
{% extends 'includes/base.html' %}


{% block title %}Equipes{% endblock title %}

{% block content %}
<!--SIDEBAR-->
{% include 'includes/sidebar.html' %}
<!-- SIDEBAR -->

<section id="content">
    <!-- NAVBAR -->
    {% include 'includes/navbar.html' %}
    <!-- NAVBAR -->


    <!-- MAIN -->
    <main>
        <h1 class="title" id="title">Equipes</h1>
        <!-- <ul class="breadcrumbs">
            <li><a href="#">Accueil</a></li>
            <li class="divider">/</li>
            <li><a class="active" href="#">Dashboard</a></li>
        </ul> -->
        <div class="div-bouton">
            <button data-bs-target="#exampleModal" data-bs-toggle="modal"><i class='bx bxs-plus-circle icon'></i>Créer
                une equipe
            </button>
        </div>
        <!-- data Table -->
        <div class="title">
            <i class="uil uil-clock-three"></i>
            <span class="text">Listes des Equipes</span>
        </div>

        <table class="table table-striped" id="example" style="width:100%">
            <thead>
            <tr>
                <th>Nom</th>
                <th>projet</th>


            </tr>
            </thead>
            <tbody>

            {% for equipe in equipes %}
            <tr>
                <td>{{ equipe.nom }}</td>
                <td>{{ equipe.projet.nom }}</td>
            </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th>Nom</th>
                <th>projet</th>


            </tr>
            </tfoot>
        </table>
        <!-- data Table -->

        <!-- formulaire modal -->

        <form action="{{ url_for('main.modalequipes') }}" method="post">
            <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="exampleModal"
                 tabindex="-1">
                <div class="modal-dialog modal-dialog-scrollable">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">equipes</h5>
                            <button aria-label="Close" class="btn-close" data-bs-dismiss="modal" type="button"></button>
                        </div>
                        <div class="modal-body">

                            <div class="mb-3">
                                <label class="form-label" for="exampleInputEmail1"> equipes</label>
                                <input aria-describedby="emailHelp" class="form-control" id="exampleInputEmail1"
                                       name="nom"
                                       type="text">
                            </div>


                                <div class="mb-3">
                                <label class="form-label" for="teamSelect"> projet :</label>
                                <select class="form-select" id="teamSelect" name="projet" required>
                                    <option value="">selectionner un projet</option>
                                    {% for projet in projets %}
                                <option value="{{ projet.id }}">{{ projet.nom }}</option>
                                {% endfor %}

                                </select>
                                    </div>

                            </div>
                            <div class="modal-footer">
                                <button button class="btn btn-secondary" data-bs-dismiss="modal"
                                        style="background-color: #D3D3D3;"
                                        type="button">Close
                                </button>
                                <button class="btn btn-primary" style="background-color: #eb7371; "
                                        type="submit">Save
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
        </form>

        <!-- formulaire modal -->
    </main>
    <!-- MAIN -->
</section>
{% endblock content %}

{% block javascripts %}
<script>
    var modal = document.getElementById("myModal");
    var btn = document.getElementById("openModal");
    var span = document.getElementsByClassName("close")[0];

    btn.onclick = function() {
        modal.style.display = "block";
    }

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
{% endblock javascripts %}

app/templates/index.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>page de connexion</title>
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <head>
<body>
<form action="{{ url_for('main.index') }}" method="POST">

    <h1>SE CONNECTER</h1>
    <p class="choose-email"></p>
    <div class="inputs">
        <input name="email" placeholder="E-mail" required type="email">
        <input name="password" placeholder="Mot de passe" required type="password">
    </div>
    <p class="inscription"> je n'ai pas de <span> compte </span> je m'en<a href="{{ url_for('main.inscription') }}">
        <span> crée un </span></a></p>
    <div align="center">
        <button type="submit">se connecter</button>
    </div>
</form>
</body>
</html>

app/templates/inscription.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>page de connexion</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <head>
    <body>
    <form method="post" action="{{ url_for('main.inscription') }}">
        <h1>INSCRIPTION</h1>
        <p class="choose-email"></p>
        <div class="inputs">
            <input type="name" name="nom" placeholder="Nom"required>
            <input type="email" name="email" placeholder="E-mail"required>
            <input type="password" name="password" placeholder="Mot de passe"required>
            <input type="password"  name="confirmer" placeholder="Confirmer votre mot de passe"required>
        </div>
       <a href="{{ url_for('main.index')}}" class="inscription"> <p>Vous avez déjà un <span>compte?</span></p></a>
        <div align="center">
           <button type="submit">s'inscrire</button>
        </div>
    </form>
</body>
</html>

app/templates/parametre.html
{% extends 'includes/base2.html' %}

{% block title %}Paramètre{% endblock title %}

{% block content %}
<!-- SIDEBAR -->
{% include 'includes/sidebar.html' %}
<!-- SIDEBAR -->

<section id="content">
    <!-- NAVBAR -->
    {% include 'includes/navbar.html' %}
    <!-- NAVBAR -->
    <h1>Paramètres</h1>
    <!-- Contenu des paramètres ici -->


    <div class="container" id="container">
        <div class="header">
            <div style="position: relative; display: inline-block;">
                <img id="toggleProfile" src="p1.jpg" alt="Photo de profil" class="profile-pic" style="cursor: pointer; border-radius: 50%; width: 100px; height: 100px;">
                <input type="file" id="changePhotoInput" style="display: none;" accept="image/*" onchange="previewImage(event)">
                <button id="changePhotoButton" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: rgba(255, 255, 255, 0.7); border: none; cursor: pointer; margin-top: 30px; margin-left: 11px; border-radius: 5px;" onclick="document.getElementById('changePhotoInput').click();">Modifier</button>
            </div>
            <h2 id="username-display">connecté</h2>
        </div>

        <div class="settings-content">


            <section class="settings-section">
                <h2 id="profileToggle"><i class="fas fa-user"></i> Informations du Profil </h2>

                <div id="profileInfo">
                    <label for="username">Nom d'utilisateur :</label>
                    <input type="text" id="username" placeholder="Votre nom d'utilisateur">

                    <label for="email">Email :</label>
                    <input type="email" id="email" placeholder="Votre email">
                </div>
            </section>

            <section class="settings-section">
                <h2><i class="fas fa-bell"></i> Notifications</h2>
                <div class="notification-settings">
                    <label for="notifications">Recevoir des notifications :</label>
                    <input type="checkbox" id="notifications" checked onclick="toggleCheckbox('sound')">
                </div>
                <div class="notification-settings">
                    <label for="sound">Activer le son :</label>
                    <input type="checkbox" id="sound" checked onclick="toggleCheckbox('notifications')">
                </div>
            </section>

            <section class="settings-section">
                <h2><i class="fas fa-paint-brush"></i> Thème</h2>
                <label for="theme">Choisir un thème :</label>
                <select id="theme" onchange="changeTheme()">
                    <option value="clair">Clair</option>
                    <option value="sombre">Sombre</option>
                </select>
            </section>

            <div class="button-container">
                <button class="save-button">Enregistrer les modifications</button>
            </div>
        </div>
    </div>

</section>
{% endblock content %}

{% block javascripts %}
<script>


    const username = "manou"; // Remplacez par le nom d'utilisateur réel
        document.getElementById("username-display").innerText = username;
        document.getElementById("username").value = username;

        // Écouteur d'événement pour le champ de saisie du nom d'utilisateur
        document.getElementById("username").addEventListener("input", function() {
            const newUsername = this.value; // Récupère la nouvelle valeur
            document.getElementById("username-display").innerText = newUsername; // Met à jour le nom d'affichage
        });

        function toggleCheckbox(otherCheckboxId) {
            const otherCheckbox = document.getElementById(otherCheckboxId);
            otherCheckbox.checked = false; // Décoche l'autre case
        }

        document.getElementById('toggleProfile').addEventListener('click', function() {
            var profileInfo = document.getElementById('profileInfo');
            profileInfo.style.display = (profileInfo.style.display === 'none' || profileInfo.style.display === '') ? 'block' : 'none';
        });

        document.getElementById('profileToggle').addEventListener('click', function() {
            var profileInfo = document.getElementById('profileInfo');
            profileInfo.style.display = (profileInfo.style.display === 'none' || profileInfo.style.display === '') ? 'block' : 'none';
        });

        function changeTheme() {
            const theme = document.getElementById("theme").value;
            const container = document.getElementById("container");
            if (theme === "sombre") {
                container.classList.add("dark-theme");
            } else {
                container.classList.remove("dark-theme");
            }
        }

        function previewImage(event) {
            const file = event.target.files[0];
            const reader = new FileReader();

            reader.onload = function(e) {
                const profilePic = document.getElementById('toggleProfile');
                profilePic.src = e.target.result; // Met à jour la source de l'image avec la nouvelle sélection
            }

            if (file) {
                reader.readAsDataURL(file); // Lit le fichier comme une URL de données
            }
        }
</script>
{% endblock javascripts %}

app/templates/projet.html
{% extends 'includes/base.html' %}

{% block title %}Projets{% endblock title %}

{% block content %}
<!--SIDEBAR-->
{% include 'includes/sidebar.html' %}
<!-- SIDEBAR -->

<section id="content">
    <!-- NAVBAR -->
    {% include 'includes/navbar.html' %}
    <!-- NAVBAR -->


    <!-- MAIN -->
    <main>
        <h1 class="title" id="title">projets</h1>
        <!-- <ul class="breadcrumbs">
            <li><a href="#">Accueil</a></li>
            <li class="divider">/</li>
            <li><a class="active" href="#">Dashboard</a></li>
        </ul> -->
        <div class="div-bouton">
            <button data-bs-target="#exampleModal" data-bs-toggle="modal"><i class='bx bxs-plus-circle icon'></i>Créer
                un projet
            </button>
        </div>
        <!-- data Table -->
        <div class="title">
            <i class="uil uil-clock-three"></i>
            <span class="text">Listes des Projets</span>
        </div>

        <div class="container_m">

            {% for projet in projets %}
            <div class="project">
                <h3>Projet 1: {{ projet.nom }}</h3>
                <p><strong>Client:</strong> {{ projet.client }}</p>
                <p><strong>Date de Début:</strong> {{ projet.date_debut }}</p>
                <p><strong>Date de Fin:</strong> {{ projet.date_fin }}</p>
                <p><strong>Statut:</strong> Terminé</p>
                <div class="footer_m">
                    <p><strong>Réalisé par:</strong> {{ projet.equipe }}</p>
                    <button onclick="location.href='#avancement'">Voir plus</button>
                </div>

            </div>
            {% endfor%}
        </div>
        <!-- data Table -->

        <!-- formulaire modal -->
        <form action="{{ url_for('main.modalprojet') }}" method="post">
            <div aria-hidden="true" aria-labelledby="exampleModalLabel" class="modal fade" id="exampleModal"
                 tabindex="-1">
                <div class="modal-dialog modal-dialog-scrollable">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Projet</h5>
                            <button aria-label="Close" class="btn-close" data-bs-dismiss="modal" type="button"></button>
                        </div>
                        <div class="modal-body">

                            <div class="mb-3">
                                <label class="form-label" for="exampleInputEmail1">Nom du projet</label>
                                <input aria-describedby="emailHelp" class="form-control" id="exampleInputEmail1"
                                       name="nom"
                                       type="text">
                            </div>

                            <div class="mb-3">
                                <label class="form-label" for="exampleInputEmail1">client</label>
                                <input aria-describedby="emailHelp" class="form-control" id="examplInputEmail1"
                                       name="client"
                                       type="text">
                            </div>

                            <div class="mb-3">
                                <label class="form-label" for="exampleInputEmail1">Description</label>
                                <textarea class="form-control" id="projectDescription" name="description"
                                          rows="2"></textarea>
                            </div>

                            <div class="mb-3">
                                <label class="form-label" for="exampleInputEmail1">Date-Debut</label>
                                <input aria-describedby="emailHelp" class="form-control" name="date_debut"
                                       type="date">
                            </div>
                            <div class="mb-3">
                                <label class="form-label" for="exampleInputEmail1">Date-Fin</label>
                                <input aria-describedby="emailHelp" class="form-control" name="date_fin"
                                       type="date">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button button class="btn btn-secondary" data-bs-dismiss="modal"
                                    style="background-color: #D3D3D3;"
                                    type="button">Close
                            </button>
                            <button class="btn btn-primary" style="background-color: #eb7371; "
                                    type="submit">Save
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!-- formulaire modal -->

    </main>
    <!-- MAIN -->
</section>
{% endblock content %}

{% block javascripts %}
<script>
    var modal = document.getElementById("myModal");
    var btn = document.getElementById("openModal");
    var span = document.getElementsByClassName("close")[0];

    btn.onclick = function() {
        modal.style.display = "block";
    }

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
{% endblock javascripts %}